name: Greenwoods
version: '${project.version}'
main: Greenwoods.Greenwoods
api-version: 1.19
authors: [ Elias, JustAndii, Gregzee ]
description: A room for all mini projects of "greenwoods.at"
website: greenwoods.at

commands:
  countdown:
    permission: greenwoods.countdown
  invisibleitemframes:
    description: "Makes item frames invisible"
  greenwoods:
    description: "Tells you the most important things"
    aliases: howtoplay